start python cf.py -d3 -w1
start python cf.py -d3 -w2
start python cf.py -d3 -w3
start python cf.py -d3 -w4
start python cf.py -d3 -w5
start python cf.py -d3 -w6
start python cf.py -d3 -w7
start python cf.py -d3 -w8
start python cf.py -d3 -w9